# Docs: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    labels:
      - 'dependencies'
    reviewers:
      - 'Shinigami92'
    versioning-strategy: increase
