version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_reviewers:
      - 'Shinigami92'
    version_requirement_updates: 'increase_versions'
