name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x, 14.x, 16.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Versions
        run: yarn versions

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.node == '14.x'
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Audit dependencies
        run: yarn audit --groups dependencies

      - name: Audit peerDependencies
        run: yarn audit --groups peerDependencies

      - name: Check outdated dependencies
        if: github.ref == 'refs/heads/main'
        run: yarn outdated
