name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16]
      fail-fast: false

    name: 'Build: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Fetch cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/.yarn/cache
            **/node_modules
          key: node-${{ matrix.node_version }}-os-${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-${{ matrix.node_version }}-os-${{ matrix.os }}-yarn-

      - name: Versions
        run: |
          echo "yarn: $(yarn --version)"
          echo "npm : $(npm --version)"
          echo "node: $(node --version)"
          echo "process.versions:"
          yarn node -p process.versions

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    name: 'Lint: node-14, ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Fetch cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/.yarn/cache
            **/node_modules
          key: node-14-os-ubuntu-latest-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-14-os-ubuntu-latest-yarn-

      - name: Prepare
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

  audit:
    runs-on: ubuntu-latest
    name: 'Audit: node-14, ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Fetch cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/.yarn/cache
            **/node_modules
          key: node-14-os-ubuntu-latest-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-14-os-ubuntu-latest-yarn-

      - name: Prepare
        run: yarn install --immutable

      - name: Audit production
        run: yarn npm audit --all --recursive --environment production

      - name: Audit all
        continue-on-error: true
        run: yarn npm audit --all --recursive

      - name: Check outdated dependencies
        continue-on-error: true
        if: github.ref == 'refs/heads/main'
        run: yarn outdated --url
